version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - rm -rf node_modules
      - npm install
      - npm run build
      - cd node_modules/bcrypt
      - node-pre-gyp install --fallback-to-build
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - chmod +x start.sh
artifacts:
  files:
    - '**/*'