"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const PlateController_1 = require("../controllers/PlateController");
const FoodController_1 = require("../controllers/FoodController");
const UserController_1 = require("../controllers/UserController");
const router = (0, express_1.Router)();
const plateController = new PlateController_1.PlateController();
const foodController = new FoodController_1.FoodController();
const usercontroller = new UserController_1.UserController();
router.post('/plate', plateController.addPlate.bind(plateController));
router.get('/allFoods', foodController.getAll.bind(foodController));
router.post('/user', usercontroller.addUser.bind(usercontroller));
router.post('/login', usercontroller.login.bind(usercontroller));
router.get('/user/:id', usercontroller.getUser.bind(usercontroller));
exports.default = router;
