"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const PlateController_1 = require("../controllers/PlateController");
const FoodController_1 = require("../controllers/FoodController");
const UserController_1 = require("../controllers/UserController");
const EmergencyController_1 = require("../controllers/EmergencyController");
const ReportController_1 = require("../controllers/ReportController");
const router = (0, express_1.Router)();
const plateController = new PlateController_1.PlateController();
const foodController = new FoodController_1.FoodController();
const usercontroller = new UserController_1.UserController();
const emergencytcontroller = new EmergencyController_1.EmergencyContoller();
const reportController = new ReportController_1.ReportController();
router.post('/plate', plateController.addPlate.bind(plateController));
router.get('/allFoods', foodController.getAll.bind(foodController));
router.post('/codebar/:code', foodController.addFoodCode.bind(foodController));
router.post('/user', usercontroller.addUser.bind(usercontroller));
router.post('/login', usercontroller.login.bind(usercontroller));
router.get('/user/:token', usercontroller.getUser.bind(usercontroller));
router.get('/test', usercontroller.testPredict.bind(usercontroller));
router.put('/update/:token', usercontroller.updateUser.bind(usercontroller));
router.post('/emergency/:token/:ind', emergencytcontroller.getFood.bind(emergencytcontroller));
router.post('/report', reportController.addReport.bind(reportController));
exports.default = router;
